
###
GET http://localhost:8080/get
Content-Type: application/json
Authorization: Basic userTo password

###
GET http://localhost:8080/adsTo/asddsfsdf/comment
Content-Type: application/json
Authorization: Basic userTo password

###
POST http://localhost:8080/login
Content-Type: application/json

{
   "username": "userTo",
   "password": "password",
   "firstName":  " asdad",
   "lastName": " asdad",
   "phone":  " asdad"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user12",
  "password": "password1"
}

###
GET http://localhost:8080/adsTo/me
Content-Type: application/json
Authorization: Basic userTo password

###
GET http://localhost:8080/user/me
Content-Type: application/json
Authorization: Basic userTo@gmail.com password

###
PATCH http://localhost:8080/user/me
Content-Type: application/json
Authorization: Basic userTo password

{
  "phone": "33333",
  "lastName": "Ivanov",
  "firstName": "Ivan",
  "email": "userTo",
  "id": 1
}

###
GET http://localhost:8080/user/1
Content-Type: application/json
Authorization: Basic userTo password

###
GET http://localhost:8080/adsTo
Content-Type: application/json
Authorization: Basic userTo password


###
POST http://localhost:8080/user/set_password
Content-Type: application/json
Authorization: Basic userTo password

{
  "newPasswordTo": "password",
  "currentPassword": "password1"
}

###
POST http://localhost:8080/adsTo
Content-Type: application/json
Authorization: Basic userTo password

{
  "image": "123",
  "price": 123,
  "description": "123",
  "pk": 1233,
  "title": "123"
}

###
GET http://localhost:8080/adsTo
Content-Type: application/json
Authorization: Basic userTo password





